#define principal main                                                                                  
#define retourner return                                                                                
#define du_coup {                                                                                       
#define voila }                                                                                         
#define court short                                                                                     
#define octet byte                                                                                      
#define entier int
#define vrai true
#define faux false
#define si if
#define sinon else
#define pendant_que while
#define pour for
#define afficher printf
#define inferieur_a <
#define superier_a >
#define egal =
#define moins -
#define plus +
#define fois *
#define diviser_par /
#define modulo %
#define strictement_egal_a ==
#define pas_egal_a !=
#define superieur_ou_egale_a >=
#define inferieur_ou_egale_a <=
#define et &&
#define ou ||
#define pas !
#define plus_egal +=
#define moins_egal -=
#define fois_egal *=
#define divise_egal /=
#define modulo_egal %=
#define casse break
#define cas case
#define caractere char
#define constante const
#define continuer continue
#define defaut default
#define faire do
#define enumerer enum
#define externe extern
#define flottant float
#define aller_a goto
#define enregistrer register
#define court short
#define signer signed
#define taille_de sizeof
#define statique static
#define structure struct
#define possible switch
#define alias typedef
#define non_signer unsigned
#define vide void
#define en_ligne inline
#define ouvrir_ficher fopen
#define fermer_ficher fclose
#define obtenir_caracter_du_ficher getc
#define mettre_caractere_dans_ficher putc
#define lire_entier getw
#define ecrire_entier putw
#define ecrire_sortie_formatter fprintf
#define lire_entree_formatter fscanf
#define lire_chaine_caracter fgets
#define erire_chaine_caracter fputs
#define fin_fichier feof
#define lire_entree_standard scanf
#define recuperer gets
#define mettre puts 
#define lire_caracter scanf